// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { resendBlock } from "./index";

export const resendBlockSchema = parseBlockSchema(resendBlock);
export const resendCredentialsSchema = parseBlockCredentials(
  resendBlock.id,
  auth,
);
